#!/usr/bin/python3
#

import os
import subprocess

_decode_ = '/usr/bin/lame --decode '
_normal_ = '/usr/bin/normalize '
_encode_ = 'oggenc -q7 --output='
_working_ = '/home/knube/Music'
_outputs_ = '/home/knube/tmp/Music'

for root, folders, files in os.walk(_working_):
	for folder in folders:
		newfold = os.path.join(root, folder).replace(_working_, _outputs_)
		print('Creating directory: ' + newfold)
		try:
			os.makedirs(newfold)
		except:
			pass
	for file in files:
		fullname = os.path.join(root, file)
		cleaname = fullname[:-4]
		wavename = cleaname + '.wav'
		if (file.lower()[-4:] == '.mp3'):
			song = file[:-4]
			print('Found: ' + fullname)
			print('Decoding: ' + song)
			decode = _decode_
			decode += '"' + fullname + '"'
			wtf1 = subprocess.run(decode, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, shell=True)
			print('Normalizing: ' + song)
			normal = _normal_
			normal += '"' + wavename + '"'
			wtf2 = subprocess.run(normal, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, shell=True)			
			print('Encoding: ' + song)
			newname = cleaname + '.ogg'
			encode = _encode_
			encode += '"' + newname + '" "' + wavename + '"'
			wtf3 = subprocess.run(encode, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, shell=True)
			print('Cleaning up temporary files')
			os.remove(wavename)
			print('Re-locating OGG file')
			os.rename(newname, os.path.join(root, file).replace(_working_, _outputs_))
		else:
			print('Ignoring: ' + fullname)
		print('----------------------------------------------------------------------')

